"""
Model Card generator service – ethical and usage transparency artifacts.

Generates Markdown Model Cards based on:
- Database model metadata
- Evaluation results
- Risk assessment data
- Usage limitations

Complements AIBOM (supply chain) with Human-Centric transparency.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import structlog

if TYPE_CHECKING:
    from app.models.evaluation import EvaluationRun
    from app.models.model import Model

logger = structlog.get_logger()


def generate_model_card(model: Model, eval_runs: list[EvaluationRun]) -> str:
    """Generate a Markdown Model Card."""

    # Calculate aggregate performance metrics
    metrics_summary = ""
    if eval_runs:
        latest_run = eval_runs[0]
        pass_rate = f"{latest_run.pass_rate * 100:.1f}%" if latest_run.pass_rate else "N/A"
        metrics_summary = f"""
### Evaluation Results
- **Latest Evaluation:** {latest_run.name} ({latest_run.completed_at})
- **Pass Rate:** {pass_rate}
- **Tests Run:** {latest_run.total_tests}
"""

    card = f"""# Model Card: {model.name}

## Model Details
- **Version:** {model.version}
- **Type:** {model.model_type.value}
- **Provider:** {model.provider_model_id or "Self-hosted"}
- **Release Date:** {model.created_at.strftime("%Y-%m-%d")}
- **Owner:** {model.owner} ({model.business_unit})
- **Risk Tier:** {model.risk_tier.value}

## Intended Use
{model.purpose or "No purpose specified."}

## Limitations & Bias
{model.known_limitations or "None documented."}

## Training Data
- **Cutoff:** {model.training_cutoff or "Unknown"}
- **Context Window:** {model.context_window} tokens

{metrics_summary}

## Ethical Considerations
- **PII Handling:** See Control Tower PII Redaction Policy
- **Governance:** Approved via Control Tower ({model.status.value})

---
*Generated by Control Tower v1.0*
"""
    logger.info("model_card_generated", model_id=model.id, version=model.version)
    return card
