########################################################################
# Runbook: API High Latency (p99 > 2s)
########################################################################

runbook_id: RB-001
title: "API High Latency – p99 > 2s SLO Breach"
severity: warning → critical (if sustained > 15min)
owner: SRE Team
last_reviewed: 2026-02-15

trigger:
  alert: api_latency_p99
  condition: "histogram_quantile(0.99, ...) > 2.0 for 5m"

impact:
  - "Frontend UI degrades: users experience slow page loads"
  - "Temporal activity timeouts may increase"
  - "Evaluation pipeline throughput drops"

diagnosis_steps:
  1_check_load:
    command: "kubectl top pods -n control-tower -l app=control-tower-backend"
    expected: "CPU < 80%, Memory < 75%"
    if_exceeded: "Scale up: kubectl scale deployment ct-backend --replicas=+2"

  2_check_database:
    command: "kubectl exec -it ct-postgres-0 -- psql -U ct_user -c 'SELECT count(*) FROM pg_stat_activity WHERE state = ''active'';'"
    expected: "< 50 active connections"
    if_exceeded: "Check for long-running queries: SELECT pid, now()-query_start AS duration, query FROM pg_stat_activity WHERE state='active' ORDER BY duration DESC LIMIT 5;"

  3_check_external_deps:
    description: "Check latency to LLM APIs, MinIO, Kafka"
    command: "curl -w '%{time_total}' -o /dev/null -s https://api.openai.com/v1/models"
    expected: "< 500ms"

  4_check_recent_deployments:
    command: "kubectl rollout history deployment/ct-backend -n control-tower"
    action: "If recent deployment, consider rollback: kubectl rollout undo deployment/ct-backend"

remediation:
  immediate:
    - "Scale backend replicas if CPU > 80%"
    - "Kill long-running database queries if blocking"
    - "Rollback recent deployment if correlated"
  short_term:
    - "Review slow query log and add missing indexes"
    - "Increase connection pool size if exhausted"
    - "Enable Redis caching for frequent read queries"
  long_term:
    - "Add read replicas for reporting queries"
    - "Implement query result caching layer"
    - "Review and optimize N+1 query patterns"

escalation:
  if_not_resolved_in: 30min
  escalate_to: model-control-lead
  if_not_resolved_in_2h: technology-risk-director
